linters:
  enable:
    - govet
    - gofmt
    - ineffassign
    - errcheck
    - staticcheck
    - gosec
    - goimports
    - unused

run:
  timeout: 5m
  skip-dirs:
    - vendor
  include:
    - cmd/
    - internal/
  exclude:
    - ^cmd/.*\.md 
    - ^internal/README.md
