name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
  pull_request:
    branches: ["main"]
    paths:
      - "**.go"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.0
          args: --timeout 3m --config .golangci.yaml
